import { DM_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/Sidebar";
import Header from "./Components/Header";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Pomo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} antialiased`}
      > <div className="flex h-screen overflow-hidden">
      <div className="w-64 flex-shrink-0">
        <Sidebar />
      </div>
      <div className="flex-1 overflow-y-auto bg-neutral-50">
        <div className="p-2.5 h-full">
          <div className="rounded-xl bg-white h-full border border-solid border-neutral-100/80">
          <Header />
          {children}
          </div>
      </div>
      </div>
    </div>
      </body>
    </html>
  );
}
